
name: Pipeline CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup do NodeJS
      uses: actions/setup-node@v4.2.0
      with:
        node-version: 16.15.1

    - name: Instalação do Mocha e dos pacotes para teste
      run:
        npm install -g mocha;
        npm install

    - name: Execução do teste
      run: mocha test/convert.js

    - name: Construção da imagem Docker
      uses: docker/build-push-action@v6.13.0
      with:   
        file: Dockerfile
        push: true
        tags: 
          jessemenegat/aula-conversao-temperatura:v1
          jessemenegat/aula-conversao-temperatura:latest
            
        
        
